"""
GH05T3 — GITHUB INTEGRATION v3
=================================
Full GitHub automation wired into the swarm bus.

Capabilities:
  • Auto-commit elite KAIROS cycles to the repo
  • Push code generated by FORGE agent
  • Create PRs for architecture upgrades
  • Receive webhooks (push, PR, issues) — emit to swarm
  • Sync Memory Palace snapshots to GitHub
  • Track repo stats in dashboard

All GitHub events are published to #github channel
and appear in the real-time conversation view.
"""

from __future__ import annotations
import asyncio
import base64
import json
import logging
import os
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import httpx

from swarm.bus import SwarmBus, MsgType, SwarmAgent, SwarmMessage

log = logging.getLogger("gh0st3.github")

GITHUB_API = "https://api.github.com"


# ─────────────────────────────────────────────
# GITHUB CLIENT
# ─────────────────────────────────────────────

class GitHubClient:
    """
    Async GitHub REST API v3 client.
    Uses PAT auth. Supports file create/update, PRs, issues.
    """

    def __init__(self, pat: str = None, repo: str = None):
        self._pat  = pat or os.environ.get("GITHUB_PAT", "")
        self._repo = repo or os.environ.get("GITHUB_REPO", "leerobber/GH05T3")
        self._http = httpx.AsyncClient(
            base_url=GITHUB_API,
            headers={
                "Authorization":        f"token {self._pat}",
                "Accept":               "application/vnd.github.v3+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=20.0,
        )

    # ── FILE OPS ──────────────────────────────

    async def get_file(self, path: str, branch: str = "main") -> Optional[dict]:
        try:
            r = await self._http.get(f"/repos/{self._repo}/contents/{path}",
                                      params={"ref": branch})
            if r.status_code == 200:
                return r.json()
        except Exception as e:
            log.error(f"[GH] get_file {path}: {e}")
        return None

    async def put_file(self, path: str, content: str, message: str,
                       branch: str = "main") -> dict:
        """Create or update a file in the repo."""
        encoded = base64.b64encode(content.encode()).decode()
        existing = await self.get_file(path, branch)
        sha = existing.get("sha") if existing else None

        payload = {
            "message": message,
            "content": encoded,
            "branch":  branch,
        }
        if sha:
            payload["sha"] = sha

        r = await self._http.put(f"/repos/{self._repo}/contents/{path}", json=payload)
        r.raise_for_status()
        return r.json()

    async def delete_file(self, path: str, message: str, branch: str = "main") -> dict:
        existing = await self.get_file(path, branch)
        if not existing:
            return {"error": "file not found"}
        r = await self._http.delete(
            f"/repos/{self._repo}/contents/{path}",
            json={"message": message, "sha": existing["sha"], "branch": branch}
        )
        r.raise_for_status()
        return r.json()

    # ── COMMITS / TREE ────────────────────────

    async def get_latest_commit(self, branch: str = "main") -> dict:
        r = await self._http.get(f"/repos/{self._repo}/branches/{branch}")
        r.raise_for_status()
        return r.json()["commit"]

    async def create_tree(self, files: dict[str, str], base_sha: str) -> str:
        """
        Create a git tree from {path: content} dict.
        Returns new tree SHA.
        """
        tree = []
        for path, content in files.items():
            tree.append({
                "path":    path,
                "mode":    "100644",
                "type":    "blob",
                "content": content,
            })
        r = await self._http.post(f"/repos/{self._repo}/git/trees",
                                   json={"base_tree": base_sha, "tree": tree})
        r.raise_for_status()
        return r.json()["sha"]

    async def create_commit(self, tree_sha: str, parent_sha: str,
                             message: str) -> str:
        """Create a commit. Returns commit SHA."""
        r = await self._http.post(
            f"/repos/{self._repo}/git/commits",
            json={
                "message": message,
                "tree":    tree_sha,
                "parents": [parent_sha],
            }
        )
        r.raise_for_status()
        return r.json()["sha"]

    async def update_ref(self, commit_sha: str, branch: str = "main"):
        """Fast-forward branch ref to commit SHA."""
        r = await self._http.patch(
            f"/repos/{self._repo}/git/refs/heads/{branch}",
            json={"sha": commit_sha, "force": False}
        )
        r.raise_for_status()

    async def push_files(self, files: dict[str, str], message: str,
                          branch: str = "main") -> str:
        """
        Atomic multi-file push. Returns commit URL.
        files: {repo_path: file_content}
        """
        head  = await self.get_latest_commit(branch)
        tree  = await self.create_tree(files, head["commit"]["tree"]["sha"])
        sha   = await self.create_commit(tree, head["sha"], message)
        await self.update_ref(sha, branch)
        url = f"https://github.com/{self._repo}/commit/{sha}"
        log.info(f"[GH] Pushed {len(files)} files: {url}")
        return url

    # ── PULL REQUESTS ─────────────────────────

    async def create_pr(self, title: str, body: str, head: str, base: str = "main") -> dict:
        r = await self._http.post(
            f"/repos/{self._repo}/pulls",
            json={"title": title, "body": body, "head": head, "base": base}
        )
        r.raise_for_status()
        return r.json()

    # ── ISSUES ────────────────────────────────

    async def create_issue(self, title: str, body: str, labels: list = None) -> dict:
        r = await self._http.post(
            f"/repos/{self._repo}/issues",
            json={"title": title, "body": body, "labels": labels or []}
        )
        r.raise_for_status()
        return r.json()

    # ── REPO INFO ─────────────────────────────

    async def repo_info(self) -> dict:
        r = await self._http.get(f"/repos/{self._repo}")
        if r.status_code == 200:
            d = r.json()
            return {
                "name":       d["name"],
                "stars":      d["stargazers_count"],
                "forks":      d["forks_count"],
                "open_issues":d["open_issues_count"],
                "url":        d["html_url"],
                "updated":    d["updated_at"],
                "default_branch": d["default_branch"],
            }
        return {"error": f"HTTP {r.status_code}"}

    async def close(self):
        await self._http.aclose()


# ─────────────────────────────────────────────
# LOCAL GIT HELPER (for bare-metal TatorTot)
# ─────────────────────────────────────────────

class LocalGit:
    """
    Wraps local git CLI for fast commits without API overhead.
    Used when TatorTot has the repo cloned locally.
    """

    def __init__(self, repo_path: str = None):
        self.repo = Path(repo_path or os.environ.get("GH05T3_REPO_PATH", ".")).resolve()

    def _run(self, *args) -> tuple[bool, str]:
        result = subprocess.run(
            ["git"] + list(args),
            cwd=self.repo,
            capture_output=True,
            text=True,
        )
        return result.returncode == 0, result.stdout + result.stderr

    def status(self) -> str:
        _, out = self._run("status", "--short")
        return out

    def add_all(self) -> bool:
        ok, _ = self._run("add", "-A")
        return ok

    def commit(self, message: str) -> tuple[bool, str]:
        return self._run("commit", "-m", message)

    def push(self, remote: str = "origin", branch: str = "main") -> tuple[bool, str]:
        return self._run("push", remote, branch)

    def pull(self) -> tuple[bool, str]:
        return self._run("pull", "--rebase")

    def commit_and_push(self, message: str,
                         branch: str = "main") -> dict:
        self.add_all()
        ok_c, out_c = self.commit(message)
        if not ok_c:
            if "nothing to commit" in out_c:
                return {"ok": True, "msg": "nothing to commit", "output": out_c}
            return {"ok": False, "error": out_c}
        ok_p, out_p = self.push(branch=branch)
        return {
            "ok":    ok_p,
            "msg":   f"Pushed to {branch}",
            "output": out_c + out_p,
        }


# ─────────────────────────────────────────────
# GITHUB SWARM AGENT
# ─────────────────────────────────────────────

class GitHubAgent(SwarmAgent):
    """
    GitHub integration as a swarm agent.
    Listens on #github channel and executes operations.
    Auto-commits elite KAIROS cycles.
    """
    ROLE        = "github"
    DESCRIPTION = "GitHub automation: commit · push · PR · sync"
    CHANNELS    = ["#github", "#broadcast"]

    def __init__(self):
        super().__init__("GITHUB")
        self._gh      = GitHubClient()
        self._git     = LocalGit()
        self._commits = 0
        self._pushes  = 0

    async def on_message(self, msg: SwarmMessage):
        content_low = msg.content.lower()

        if msg.msg_type == MsgType.TASK or msg.msg_type == MsgType.GITHUB:
            if "commit" in content_low:
                await self._do_commit(msg)
            elif "push" in content_low:
                await self._do_push(msg)
            elif "sync" in content_low or "memory" in content_low:
                await self._sync_memory(msg)
            elif "status" in content_low:
                await self._repo_status(msg)

        # Auto-commit elite KAIROS cycles
        if msg.msg_type == MsgType.KAIROS and msg.metadata.get("is_elite"):
            await self._auto_commit_elite(msg)

    async def _do_commit(self, msg: SwarmMessage):
        commit_msg = msg.metadata.get("commit_msg", msg.content)
        await self.think(f"GITHUB: Committing — '{commit_msg[:50]}'")
        result = self._git.commit_and_push(commit_msg)
        self._commits += 1
        await self.say(
            f"{'✅' if result['ok'] else '❌'} Commit: {result.get('msg', result.get('error'))}",
            channel="#github",
            msg_type=MsgType.GITHUB,
            result=result,
        )

    async def _do_push(self, msg: SwarmMessage):
        files = msg.metadata.get("files", {})
        commit_msg = msg.metadata.get("commit_msg", "🖤 GH05T3 auto-push")
        if not files:
            await self.say("No files provided for push", channel="#github", msg_type=MsgType.ERROR)
            return
        try:
            url = await self._gh.push_files(files, commit_msg)
            self._pushes += 1
            await self.say(
                f"✅ Pushed {len(files)} files → {url}",
                channel="#github", msg_type=MsgType.GITHUB,
                commit_url=url,
            )
        except Exception as e:
            await self.say(f"❌ Push failed: {e}", channel="#github", msg_type=MsgType.ERROR)

    async def _sync_memory(self, msg: SwarmMessage):
        """Push Memory Palace snapshot to GitHub."""
        mem_path = Path("memory/palace.db")
        if not mem_path.exists():
            await self.say("Memory DB not found", channel="#github", msg_type=MsgType.ERROR)
            return

        # Export conversation log
        conv_path = Path("memory/conversations.jsonl")
        files = {}
        if conv_path.exists():
            files["memory/conversations.jsonl"] = conv_path.read_text()

        kairos_path = Path("evolution/kairos_log.jsonl")
        if kairos_path.exists():
            files["evolution/kairos_log.jsonl"] = kairos_path.read_text()

        if files:
            try:
                url = await self._gh.push_files(
                    files,
                    f"🧠 [GH05T3] Memory sync — {time.strftime('%Y-%m-%d %H:%M')}"
                )
                await self.say(
                    f"✅ Memory synced to GitHub: {url}",
                    channel="#github", msg_type=MsgType.GITHUB,
                )
            except Exception as e:
                await self.say(f"❌ Memory sync failed: {e}", channel="#github", msg_type=MsgType.ERROR)

    async def _repo_status(self, msg: SwarmMessage):
        try:
            info = await self._gh.repo_info()
            await self.say(
                f"📊 Repo: {info.get('name')} | ⭐ {info.get('stars')} | "
                f"🍴 {info.get('forks')} | Issues: {info.get('open_issues')}",
                channel="#github", msg_type=MsgType.GITHUB,
                repo_info=info,
            )
        except Exception as e:
            await self.say(f"Repo status unavailable: {e}", channel="#github", msg_type=MsgType.ERROR)

    async def _auto_commit_elite(self, msg: SwarmMessage):
        """Auto-commit elite KAIROS cycle."""
        cycle_id = msg.metadata.get("cycle_id", "?")
        score    = msg.metadata.get("score", 0.0)
        commit_msg = f"[KAIROS Elite #{cycle_id}] score={score:.2f} -- auto-committed"
        self._git.add_all()
        self._git.commit(commit_msg)
        await self.say(
            f"Elite cycle #{cycle_id} (score {score:.2f}) committed to GitHub",
            channel="#github", msg_type=MsgType.GITHUB,
        )

    # ── CROSS-INSTANCE GITHUB RELAY SYNC ─────────────────────────────────────

    async def push_relay(self) -> dict:
        """Push this instance's memory/KAIROS data to GitHub under mesh/sync/<label>/.
        Any other instance with a GitHub PAT can pull it — no direct TCP needed."""
        label = os.environ.get("INSTANCE_LABEL", "unknown")
        branch = os.environ.get("GITHUB_BRANCH", "main")
        files: dict[str, str] = {}

        base = Path(__file__).parent.parent
        for src, dest in [
            (base / "memory" / "conversations.jsonl", f"mesh/sync/{label}/conversations.jsonl"),
            (base / "evolution" / "kairos_log.jsonl",  f"mesh/sync/{label}/kairos_log.jsonl"),
        ]:
            if src.exists() and src.stat().st_size > 0:
                files[dest] = src.read_text(errors="replace")

        # Write a small manifest so peers know when this instance last synced
        files[f"mesh/sync/{label}/manifest.json"] = json.dumps({
            "label":    label,
            "role":     os.environ.get("INSTANCE_ROLE", "peer"),
            "url":      os.environ.get("INSTANCE_URL", ""),
            "synced_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "files":    list(files.keys()),
        }, indent=2)

        if not files:
            return {"ok": False, "reason": "no local data to push"}

        try:
            url = await self._gh.push_files(
                files, f"[GH05T3 mesh] {label} sync {time.strftime('%Y-%m-%d %H:%M')}", branch
            )
            log.info("[GH relay] pushed %d files for %s", len(files), label)
            return {"ok": True, "files": len(files), "url": url, "label": label}
        except Exception as e:
            log.warning("[GH relay] push failed: %s", e)
            return {"ok": False, "error": str(e)}

    async def pull_relay(self) -> dict:
        """Pull peer memory from GitHub mesh/sync/ and merge into local KAIROS log."""
        branch = os.environ.get("GITHUB_BRANCH", "main")
        my_label = os.environ.get("INSTANCE_LABEL", "unknown")
        base = Path(__file__).parent.parent

        # List all peers by scanning mesh/sync/ directory
        try:
            r = await self._gh._http.get(
                f"/repos/{self._gh._repo}/contents/mesh/sync",
                params={"ref": branch}
            )
            if r.status_code != 200:
                return {"ok": False, "reason": f"mesh/sync not found (HTTP {r.status_code})"}
            peers = [item["name"] for item in r.json() if item["type"] == "dir" and item["name"] != my_label]
        except Exception as e:
            return {"ok": False, "error": str(e)}

        merged = 0
        for peer_label in peers:
            for filename, local_path in [
                ("kairos_log.jsonl", base / "evolution" / "kairos_log.jsonl"),
                ("conversations.jsonl", base / "memory" / "conversations.jsonl"),
            ]:
                file_data = await self._gh.get_file(f"mesh/sync/{peer_label}/{filename}", branch)
                if not file_data:
                    continue
                try:
                    remote_text = base64.b64decode(file_data["content"]).decode(errors="replace")
                    remote_lines = set(remote_text.strip().splitlines())
                    local_lines: set[str] = set()
                    if local_path.exists():
                        local_lines = set(local_path.read_text(errors="replace").strip().splitlines())
                    new_lines = remote_lines - local_lines
                    if new_lines:
                        local_path.parent.mkdir(parents=True, exist_ok=True)
                        with open(local_path, "a") as f:
                            f.write("\n".join(sorted(new_lines)) + "\n")
                        merged += len(new_lines)
                        log.info("[GH relay] merged %d new lines from %s/%s", len(new_lines), peer_label, filename)
                except Exception as e:
                    log.warning("[GH relay] merge error %s/%s: %s", peer_label, filename, e)

        return {"ok": True, "peers_found": len(peers), "lines_merged": merged}

    @property
    def stats(self) -> dict:
        base = super().stats
        return {**base, "commits": self._commits, "pushes": self._pushes}

    async def close(self):
        await self._gh.close()


# ─────────────────────────────────────────────
# WEBHOOK RECEIVER (FastAPI router)
# ─────────────────────────────────────────────

def create_github_webhook_router():
    """
    Returns a FastAPI APIRouter that receives GitHub webhooks
    and publishes them to the SwarmBus.
    Mount at /webhooks/github.
    """
    from fastapi import APIRouter, Request, Header, HTTPException
    import hmac, hashlib

    router = APIRouter(prefix="/webhooks/github")
    bus    = SwarmBus.instance()
    secret = os.environ.get("GITHUB_WEBHOOK_SECRET", "").encode()

    def _verify(body: bytes, sig: str) -> bool:
        if not secret:
            return True   # No secret configured — accept all
        expected = "sha256=" + hmac.new(secret, body, hashlib.sha256).hexdigest()
        return hmac.compare_digest(expected, sig or "")

    @router.post("")
    async def receive_webhook(
        request: Request,
        x_github_event: str = Header(default=""),
        x_hub_signature_256: str = Header(default=""),
    ):
        body = await request.body()
        if not _verify(body, x_hub_signature_256):
            raise HTTPException(403, "Invalid webhook signature")

        payload = json.loads(body)
        event   = x_github_event

        # Map events to human-readable messages
        if event == "push":
            pusher = payload.get("pusher", {}).get("name", "unknown")
            ref    = payload.get("ref", "")
            count  = len(payload.get("commits", []))
            content = f"📦 Push by {pusher} → {ref} ({count} commits)"
        elif event == "pull_request":
            action = payload.get("action", "")
            title  = payload.get("pull_request", {}).get("title", "")
            content = f"🔀 PR {action}: {title}"
        elif event == "issues":
            action = payload.get("action", "")
            title  = payload.get("issue", {}).get("title", "")
            content = f"🐛 Issue {action}: {title}"
        elif event == "release":
            name = payload.get("release", {}).get("name", "")
            content = f"🚀 Release: {name}"
        else:
            content = f"GitHub event: {event}"

        await bus.emit(
            src="GITHUB-WEBHOOK",
            content=content,
            channel="#github",
            msg_type=MsgType.GITHUB,
            gh_event=event,
            payload=payload,
        )

        return {"ok": True, "event": event}

    return router
